
import {
  GoogleGenAI,
  Modality,
  VideoGenerationReferenceType,
} from '@google/genai';
import { GenerateGreetingParams, VoiceGender, VeoModel } from '../types';

/**
 * Helper to decode base64 audio and get its duration in seconds.
 * Gemini TTS output is raw PCM at 24kHz 16-bit mono.
 */
async function getAudioDuration(base64Data: string): Promise<number> {
  try {
    const binaryString = atob(base64Data);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }
    // 2 bytes per sample (16-bit), 24000 samples per second
    const duration = (bytes.length / 2) / 24000; 
    return duration;
  } catch (e) {
    console.warn("[Studio] Could not determine audio duration accurately, defaulting to 10s", e);
    return 10;
  }
}

/**
 * Generates a cinematic greeting video using Gemini Veo models.
 * Dynamically extends the production to match or exceed the audio script duration.
 * Ensures "Director's Cut" produces a video of at least 15 seconds.
 */
export const generateGreetingVideo = async (
  params: GenerateGreetingParams & { audioDuration?: number }
): Promise<{ objectUrl: string; blob: Blob }> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  // 1. Calculate Target Duration
  // Default segment length for Veo is 7 seconds.
  const segmentLength = 7;
  const audioDuration = params.audioDuration || 7;
  
  // Initial target is audio length + small buffer (2s) to avoid abrupt cuts
  let targetDuration = Math.ceil(audioDuration) + 2; 
  
  // "Director's Cut" logic: Force a minimum of 15 seconds.
  // This will result in at least 3 segments (approx 21s) since segments are added in 7s blocks.
  if (params.extended) {
    targetDuration = Math.max(targetDuration, 15);
  }

  const needsExtension = targetDuration > segmentLength;

  /**
   * CRITICAL: If any extension is required, the entire production chain 
   * MUST use 'veo-3.1-generate-preview' to ensure compatibility 
   * with the extension endpoint. 
   */
  const modelToUse = (needsExtension || params.userPhoto) 
    ? 'veo-3.1-generate-preview' 
    : 'veo-3.1-fast-generate-preview';

  const visualContext = params.scenicDescription && params.scenicDescription.trim().length > 0 
    ? `Visual Scene: ${params.scenicDescription}` 
    : `Visual Theme: ${params.theme}`;

  const cinematicPrompt = `
    A cinematic, high-quality holiday greeting video for ${params.occasion}.
    ${visualContext}. 
    Atmosphere: Joyful, celebratory, professional cinematic lighting, 8k resolution feel.
    Visual storytelling context: ${params.message.substring(0, 1000)}
  `.trim();

  const config: any = {
    numberOfVideos: 1,
    resolution: '720p',
    aspectRatio: params.userPhoto ? '16:9' : params.aspectRatio,
  };

  const initialPayload: any = {
    model: modelToUse,
    prompt: cinematicPrompt,
    config: config,
  };

  if (params.userPhoto) {
    initialPayload.config.referenceImages = [{
      image: {
        imageBytes: params.userPhoto.base64,
        mimeType: params.userPhoto.file.type || 'image/jpeg',
      },
      referenceType: VideoGenerationReferenceType.ASSET,
    }];
  }

  try {
    console.log(`[Studio] Starting Production. Script: ${audioDuration.toFixed(1)}s. Target Video: ${targetDuration}s.`);
    
    // 2. Initial Segment Generation (0-7s)
    let operation = await ai.models.generateVideos(initialPayload);
    while (!operation.done) {
      await new Promise((resolve) => setTimeout(resolve, 10000));
      operation = await ai.operations.getVideosOperation({ operation: operation });
    }

    let currentVideoAsset = operation.response?.generatedVideos?.[0]?.video;
    if (!currentVideoAsset) throw new Error("Initial production segment failed to generate.");
    
    let currentProducedDuration = segmentLength;
    
    // 3. Iterative Extension Loop
    // Extends the video in 7s increments until targetDuration is met or exceeded.
    while (currentProducedDuration < targetDuration) {
      console.log(`[Studio] Extending Production. Currently at ${currentProducedDuration}s. Target: ${targetDuration}s.`);
      
      /**
       * BACKEND INDEXING DELAY (Mitigation for 400 Error):
       * The error "Input video must be a video that was generated by VEO that has been processed" 
       * occurs if we call extend too quickly. We wait 35 seconds to ensure the URI is 
       * fully processed and indexed by the backend for the next extension.
       */
      await new Promise((resolve) => setTimeout(resolve, 35000));

      const extensionPayload = {
        model: 'veo-3.1-generate-preview',
        prompt: `Continue the cinematic celebration for ${params.occasion}. Seamless visual flow from the previous scene, maintaining lighting, characters, and festive atmosphere.`,
        video: currentVideoAsset,
        config: {
          numberOfVideos: 1,
          resolution: '720p',
          aspectRatio: config.aspectRatio,
        }
      };

      let extendOp = await ai.models.generateVideos(extensionPayload);
      while (!extendOp.done) {
        await new Promise((resolve) => setTimeout(resolve, 10000));
        extendOp = await ai.operations.getVideosOperation({ operation: extendOp });
      }
      
      const extendedAsset = extendOp.response?.generatedVideos?.[0]?.video;
      if (extendedAsset) {
        currentVideoAsset = extendedAsset;
        currentProducedDuration += segmentLength;
      } else {
        console.warn("[Studio] Extension operation returned no video asset. Finalizing.");
        break; 
      }
    }

    const downloadLink = currentVideoAsset?.uri;
    if (downloadLink) {
      // Fetch the final merged MP4 bytes
      const response = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
      if (!response.ok) throw new Error('Failed to retrieve finalized production file.');
      
      const blob = await response.blob();
      console.log(`[Studio] Production Successful. Total length approx ${currentProducedDuration}s.`);
      return { objectUrl: URL.createObjectURL(blob), blob };
    }
  } catch (error: any) {
    console.error("[Studio] Video Production Pipeline Failure:", error);
    throw error;
  }

  throw new Error('Video production pipeline failed to yield a final asset.');
};

/**
 * Generates audio for a greeting message using Gemini TTS.
 * Returns duration for video synchronization.
 */
export const generateGreetingVoice = async (text: string, voice: VoiceGender): Promise<{ base64: string, duration: number } | null> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const voiceMap: Record<VoiceGender, string> = {
    [VoiceGender.MALE_TENOR]: 'Kore',
    [VoiceGender.MALE_BASS]: 'Puck',
    [VoiceGender.FEMALE]: 'Charon'
  };

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-preview-tts",
      contents: [{ parts: [{ text: text }] }],
      config: {
        responseModalities: [Modality.AUDIO],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: { voiceName: voiceMap[voice] },
          },
        },
      },
    });

    const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
    if (!base64Audio) return null;

    const duration = await getAudioDuration(base64Audio);
    return { base64: base64Audio, duration };
  } catch (e) {
    console.error("Voice Generation failed:", e);
    return null;
  }
};
