
import {
  GoogleGenAI,
  Modality,
  VideoGenerationReferenceType,
} from '@google/genai';
import { GenerateGreetingParams, VoiceGender, VeoModel, Occasion } from '../types';

/**
 * Helper to decode base64 audio and get its duration in seconds.
 * Gemini TTS output is raw PCM at 24kHz 16-bit mono.
 */
async function getAudioDuration(base64Data: string): Promise<number> {
  try {
    const binaryString = atob(base64Data);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }
    // 2 bytes per sample (16-bit), 24000 samples per second
    const duration = (bytes.length / 2) / 24000; 
    return duration;
  } catch (e) {
    console.warn("[Studio] Could not determine audio duration accurately, defaulting to 10s", e);
    return 10;
  }
}

/**
 * Generates a cinematic greeting video using Gemini Veo models.
 * Dynamically extends the production to match or exceed the audio script duration.
 * Ensures "Director's Cut" produces a video of at least 15 seconds.
 */
export const generateGreetingVideo = async (
  params: GenerateGreetingParams & { audioDuration?: number }
): Promise<{ objectUrl: string; blob: Blob }> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  // 1. Calculate Target Duration
  const segmentLength = 7; // Veo standard segment length
  const audioDuration = params.audioDuration || 7;
  
  // Video must be longer than the audio to avoid cutting mid-sentence
  let targetDuration = Math.ceil(audioDuration) + 2; 
  
  // User requested: "Director's Cut" reset to 15 seconds.
  if (params.extended) {
    targetDuration = Math.max(targetDuration, 15);
  }

  const needsExtension = targetDuration > segmentLength;

  /**
   * CRITICAL: If any extension is required, the entire production chain 
   * MUST use 'veo-3.1-generate-preview' to ensure compatibility 
   * and avoid the 400 processing error.
   */
  const modelToUse = (needsExtension || params.userPhoto) 
    ? 'veo-3.1-generate-preview' 
    : 'veo-3.1-fast-generate-preview';

  // "None" Occasion logic: Use all words of the script for Awesome Cinematic Visuals
  const visualContext = params.scenicDescription && params.scenicDescription.trim().length > 0 
    ? `Visual Environment: ${params.scenicDescription}` 
    : (params.occasion !== Occasion.NONE ? `Visual Theme: ${params.theme}` : '');

  const occasionHeader = params.occasion !== Occasion.NONE 
    ? `Cinematic holiday greeting for ${params.occasion}` 
    : `Awesome Cinematic Masterpiece with conceptual narrative`;

  const scriptPriority = params.occasion === Occasion.NONE 
    ? `IMPORTANT: This video has no specific occasion. Use the ENTIRE script text below to create the Awesome Cinematic Visuals, interpreting the imagery, mood, and story directly from these words: "${params.message}"`
    : `Visual narrative based on this script: "${params.message.substring(0, 500)}..."`;

  const cinematicPrompt = `
    ${occasionHeader}.
    ${visualContext}. 
    Style: High-end professional cinematic lighting, 8k resolution textures, epic atmosphere, detailed textures.
    ${scriptPriority}
  `.trim();

  const config: any = {
    numberOfVideos: 1,
    resolution: '720p',
    aspectRatio: params.userPhoto ? '16:9' : params.aspectRatio,
  };

  const initialPayload: any = {
    model: modelToUse,
    prompt: cinematicPrompt,
    config: config,
  };

  if (params.userPhoto) {
    initialPayload.config.referenceImages = [{
      image: {
        imageBytes: params.userPhoto.base64,
        mimeType: params.userPhoto.file.type || 'image/jpeg',
      },
      referenceType: VideoGenerationReferenceType.ASSET,
    }];
  }

  try {
    console.log(`[Studio] Starting Production. Script Length: ${audioDuration.toFixed(1)}s. Target Video Length: ${targetDuration}s.`);
    
    // 2. Initial Segment Generation (0-7s)
    let operation = await ai.models.generateVideos(initialPayload);
    while (!operation.done) {
      await new Promise((resolve) => setTimeout(resolve, 10000));
      operation = await ai.operations.getVideosOperation({ operation: operation });
    }

    let currentVideoAsset = operation.response?.generatedVideos?.[0]?.video;
    if (!currentVideoAsset) throw new Error("Initial production segment failed.");
    
    let currentProducedDuration = segmentLength;
    
    // 3. Iterative Extension Loop
    while (currentProducedDuration < targetDuration) {
      console.log(`[Studio] Extending Production. Progress: ${currentProducedDuration}s / ${targetDuration}s.`);
      
      /**
       * CRITICAL MITIGATION FOR 400 ERROR:
       * "Input video must be a video that was generated by VEO that has been processed."
       * This error indicates the video URI isn't ready for extension immediately after 'done'.
       * We increase wait time to 45 seconds to ensure indexing is complete.
       */
      console.log("[Studio] Waiting 45s for backend indexing...");
      await new Promise((resolve) => setTimeout(resolve, 45000));

      const extensionPayload = {
        model: 'veo-3.1-generate-preview',
        prompt: `Continue the cinematic visual narrative, flowing seamlessly from the previous shot. ${params.occasion === Occasion.NONE ? 'Further explore the visual world described in the script: ' + params.message.substring(0, 200) : 'Maintain lighting and character consistency for ' + params.occasion + '.'}`,
        video: currentVideoAsset,
        config: {
          numberOfVideos: 1,
          resolution: '720p',
          aspectRatio: config.aspectRatio,
        }
      };

      let extendOp = await ai.models.generateVideos(extensionPayload);
      while (!extendOp.done) {
        await new Promise((resolve) => setTimeout(resolve, 10000));
        extendOp = await ai.operations.getVideosOperation({ operation: extendOp });
      }
      
      const extendedAsset = extendOp.response?.generatedVideos?.[0]?.video;
      if (extendedAsset) {
        currentVideoAsset = extendedAsset;
        currentProducedDuration += segmentLength;
      } else {
        console.warn("[Studio] Extension attempt failed to return a new asset. Finalizing.");
        break; 
      }
    }

    const downloadLink = currentVideoAsset?.uri;
    if (downloadLink) {
      const response = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
      if (!response.ok) throw new Error('Failed to retrieve finalized production file.');
      
      const blob = await response.blob();
      console.log(`[Studio] Production Successful. Final length: ~${currentProducedDuration}s.`);
      return { objectUrl: URL.createObjectURL(blob), blob };
    }
  } catch (error: any) {
    console.error("[Studio] Video Production Failure:", error);
    throw error;
  }

  throw new Error('Video production pipeline failed.');
};

/**
 * Generates audio for a greeting message using Gemini TTS.
 * Returns duration for video synchronization.
 */
export const generateGreetingVoice = async (text: string, voice: VoiceGender): Promise<{ base64: string, duration: number } | null> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const voiceMap: Record<VoiceGender, string> = {
    [VoiceGender.MALE_TENOR]: 'Kore',
    [VoiceGender.MALE_BASS]: 'Puck',
    [VoiceGender.FEMALE]: 'Charon'
  };

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-preview-tts",
      contents: [{ parts: [{ text: text }] }],
      config: {
        responseModalities: [Modality.AUDIO],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: { voiceName: voiceMap[voice] },
          },
        },
      },
    });

    const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
    if (!base64Audio) return null;

    const duration = await getAudioDuration(base64Audio);
    return { base64: base64Audio, duration };
  } catch (e) {
    console.error("Voice Generation failed:", e);
    return null;
  }
};
